
#line 3 "tokens.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[437] =
    {   0,
        0,    0,   64,   62,   60,   61,   56,   62,   55,   62,
       62,   62,   62,   62,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   60,   55,    0,
       55,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   59,   57,
       58,   54,   54,   52,   52,   52,   44,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   40,   52,
       52,   52,   52,   52,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   54,   54,   48,

       39,   52,   52,   52,   47,   52,   52,   52,   52,   52,
       38,   52,   52,   52,   52,   52,   52,    0,   15,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       54,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       45,   52,   52,   52,   37,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   32,   31,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   54,   52,   52,   52,   52,   52,   41,   52,   52,
       52,   52,   46,   52,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   19,    0,    0,   54,    1,
        2,   36,   42,   43,   52,   52,   35,   52,   52,   22,
        0,    0,    0,    0,    0,   29,    0,   28,    0,    0,
        0,   33,    0,    0,    0,    0,    0,    0,    0,    5,
        6,    0,   54,   52,   52,    3,   52,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   14,    0,   30,    0,
        0,    0,    0,    0,    0,   54,   50,   49,   52,    0,
        0,    0,    0,    0,   25,    0,    9,    0,    0,    0,
        0,    0,    0,    0,    0,   53,   52,    0,   27,   20,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   51,    0,    0,    0,    0,    0,    0,    0,
        0,   24,    0,   21,    0,    0,    0,   34,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   26,    0,    4,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   23,    0,    0,    0,    0,    0,    0,    0,
        0,   16,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   18,    0,    0,    0,    0,

        0,    0,   13,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   17,    0,    0,    0,
        0,    0,    0,    7,    0,    0,    0,    0,    0,   11,
        0,    0,   12,    8,   10,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    4,    4,    1,    5,    6,    4,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    9,   10,
       11,   12,   13,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
        1,    1,    1,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    1,    1,    2,    1,    2,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    2,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[441] =
    {   0,
        0,    0,  871,  872,  868,  872,  872,  862,   61,   55,
      857,  848,  838,   53,   92,    0,   75,   96,   50,   53,
      107,   52,  107,   93,   93,   99,  107,  843,  837,  836,
       84,  123,  104,  113,  142,  111,  109,  116,  139,  153,
      158,  161,  142,  159,  145,  142,  154,  839,  872,  872,
      872,    0,  148,    0,  158,  169,    0,  168,  163,  157,
      174,  171,  163,  166,  159,  170,  168,  188,    0,  194,
      187,  211,  193,  209,  196,  205,  203,  205,  201,  208,
      204,  217,  203,  218,  207,  229,  222,  212,  226,  224,
      217,  231,  236,  221,  224,  236,  244,    0,  238,    0,

        0,  257,  266,  260,    0,  251,  270,  260,  264,  265,
        0,  270,  258,  275,  260,  280,  268,  275,  872,  276,
      287,  276,  286,  287,  284,  289,  273,  291,  298,  300,
      303,  321,  319,  324,  323,  314,  308,  321,  326,  310,
      335,  324,  330,  335,  321,  330,  318,  331,  332,  343,
        0,  338,  340,  349,    0,  349,  370,  366,  356,  369,
      358,  371,  361,  379,  371,  364,  371,  872,  872,  377,
      369,  387,  379,  378,  385,  375,  387,  381,  379,  385,
      395,  384,  409,  401,  400,  409,  417,    0,  421,  423,
      413,  429,    0,  836,  421,  835,  416,  436,  424,  425,

      426,  434,  424,  437,  442,  428,  446,  441,  431,  447,
      439,  451,  449,  450,  450,  872,  465,  464,  474,    0,
        0,    0,    0,    0,  458,  460,    0,  474,  468,  872,
      477,  481,  477,  471,  490,  872,  479,  872,  477,  484,
      481,  872,  480,  484,  484,  501,  505,  501,  503,  872,
      872,  493,  507,  518,  521,    0,  527,  528,  523,  520,
      526,  522,  529,  539,  520,  526,  872,  542,  872,  543,
      542,  532,  545,  542,  555,  543,    0,    0,  545,  545,
      546,  542,  541,  557,  834,  833,  872,  567,  832,  559,
      560,  585,  586,  587,  582,    0,  590,  585,  596,  872,

      579,  577,  591,  600,  601,  589,  587,  599,  590,  606,
      597,  830,    0,  593,  601,  129,  609,  601,  613,  608,
      612,  872,  616,  872,  126,  614,  628,  872,   90,  640,
       89,  641,  628,   87,  644,  636,  635,  633,  635,  649,
      649,  640,  642,  651,  646,  660,  872,  646,  872,  660,
      660,  661,  650,  648,  655,  656,  669,  680,  685,  692,
      694,  695,  701,  689,  699,  691,  703,  692,  703,  706,
      707,  701,  695,  713,  713,  703,  705,  717,  701,  707,
      714,  872,  709,  719,  724,  735,  722,  733,  739,  734,
      742,  737,  754,  750,  741,  872,  757,  753,  759,  755,

      758,  748,  872,  761,  766,  763,  758,  754,  766,  756,
      758,  758,  768,  783,  778,  787,  872,  797,  788,  793,
      796,  796,  797,  872,  799,  795,  801,  802,  798,  872,
      799,  802,  872,  872,  872,  872,  861,   73,  863,  865
    } ;

static yyconst flex_int16_t yy_def[441] =
    {   0,
      436,    1,  436,  436,  436,  436,  436,  436,  436,  436,
      437,  436,  436,  438,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  437,  436,  436,
      436,  440,  440,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  440,  440,  439,

      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      440,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  440,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  440,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  440,  439,  439,  439,  439,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  440,  439,  439,  439,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  440,  439,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  439,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,    0,  436,  436,  436,  436
    } ;

static yyconst flex_int16_t yy_nxt[939] =
    {   0,
        4,    5,    6,    7,    7,    8,    9,   10,   11,   12,
        7,   13,   14,   15,   16,   16,   17,   18,   19,   16,
       16,   20,   16,   16,   16,   21,   22,   23,   24,   16,
       16,   25,   26,   16,   16,   27,   16,   16,   16,    4,
       15,   16,   16,   17,   18,   19,   16,   16,   20,   16,
       16,   16,   21,   22,   23,   24,   16,   16,   25,   26,
       16,   16,   27,   16,   16,   16,   30,   31,   32,   53,
       33,   34,   35,   36,   37,   52,   38,   63,   64,   67,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   30,
       31,  345,   58,  342,  340,   32,   53,   33,   34,   35,

       36,   37,   59,   38,   63,   64,   67,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   55,   60,   56,   58,
       65,   68,   61,   71,   57,   72,   73,   74,   66,   59,
      337,   78,   62,  330,   79,   85,   86,   69,   75,   76,
       80,   70,   87,   55,   60,   56,   81,   65,   68,   61,
       71,   57,   72,   73,   74,   66,   88,   77,   78,   62,
       82,   79,   85,   86,   69,   75,   76,   80,   70,   87,
       89,   83,   90,   81,   91,   93,   94,   95,   84,   96,
       97,   99,  100,   88,   77,  101,  102,   82,  103,  104,
      105,   92,  106,  107,  108,  109,  110,   89,   83,   90,

      111,   91,   93,   94,   95,   84,   96,   97,   99,  100,
      112,  113,  101,  102,  114,  103,  104,  105,   92,  106,
      107,  108,  109,  110,  115,  116,  117,  111,  118,  119,
      120,  121,  122,  123,  124,  125,  126,  112,  113,  127,
      128,  114,  129,  130,  131,  132,  133,  134,  135,  136,
      137,  115,  116,  117,  138,  118,  119,  120,  121,  122,
      123,  124,  125,  126,  139,  140,  127,  128,  141,  129,
      130,  131,  132,  133,  134,  135,  136,  137,  142,  143,
      144,  138,  145,  146,  147,  148,  149,  150,  151,  152,
      153,  139,  140,  154,  155,  141,  156,  157,  161,  162,

      163,  164,  165,  158,  166,  142,  143,  144,  167,  145,
      146,  147,  148,  149,  150,  151,  152,  153,  159,  160,
      154,  155,  168,  156,  157,  161,  162,  163,  164,  165,
      158,  166,  169,  170,  171,  167,  172,  173,  174,  175,
      176,  177,  178,  179,  181,  159,  160,  180,  182,  168,
      183,  184,  185,  186,  187,  188,  189,  190,  191,  169,
      170,  171,  192,  172,  173,  174,  175,  176,  177,  178,
      179,  181,  193,  194,  180,  182,  195,  183,  184,  185,
      186,  187,  188,  189,  190,  191,  196,  197,  198,  192,
      199,  200,  201,  202,  203,  204,  205,  206,  207,  193,

      194,  208,  209,  195,  210,  211,  212,  213,  214,  215,
      216,  217,  218,  196,  197,  198,  219,  199,  200,  201,
      202,  203,  204,  205,  206,  207,  220,  221,  208,  209,
      222,  210,  211,  212,  213,  214,  215,  216,  217,  218,
      223,  224,  225,  219,  226,  227,  228,  230,  232,  233,
      234,  235,  236,  220,  221,  237,  238,  222,  239,  240,
      241,  242,  243,  244,  245,  246,  247,  223,  224,  225,
      248,  226,  227,  228,  230,  232,  233,  234,  235,  236,
      249,  250,  237,  238,  251,  239,  240,  241,  242,  243,
      244,  245,  246,  247,  252,  253,  254,  248,  255,  256,

      257,  258,  259,  260,  261,  262,  263,  249,  250,  265,
      266,  251,  267,  264,  268,  269,  270,  271,  272,  273,
      274,  252,  253,  254,  275,  255,  256,  257,  258,  259,
      260,  261,  262,  263,  276,  277,  265,  266,  278,  267,
      264,  268,  269,  270,  271,  272,  273,  274,  279,  280,
      281,  275,  282,  283,  284,  285,  286,  287,  288,  289,
      290,  276,  277,  291,  292,  278,  293,  294,  295,  296,
      297,  298,  299,  300,  301,  279,  280,  281,  302,  282,
      283,  284,  285,  286,  287,  288,  289,  290,  305,  307,
      291,  292,  308,  293,  294,  295,  296,  297,  298,  299,

      300,  301,  309,  310,  311,  302,  312,  313,  314,  315,
      316,  317,  318,  319,  320,  305,  307,  321,  322,  308,
      323,  324,  325,  326,  328,  329,  331,  332,  333,  309,
      310,  311,  334,  312,  313,  314,  315,  316,  317,  318,
      319,  320,  335,  336,  321,  322,  338,  323,  324,  325,
      326,  328,  329,  331,  332,  333,  339,  341,  343,  334,
      344,  346,  347,  348,  349,  350,  351,  352,  353,  335,
      336,  354,  355,  338,  356,  357,  358,  359,  360,  361,
      362,  363,  364,  339,  341,  343,  365,  344,  346,  347,
      348,  349,  350,  351,  352,  353,  366,  367,  354,  355,

      368,  356,  357,  358,  359,  360,  361,  362,  363,  364,
      369,  370,  371,  365,  372,  373,  374,  375,  376,  377,
      378,  379,  380,  366,  367,  381,  382,  368,  383,  384,
      385,  386,  387,  388,  389,  390,  391,  369,  370,  371,
      392,  372,  373,  374,  375,  376,  377,  378,  379,  380,
      393,  394,  381,  382,  395,  383,  384,  385,  386,  387,
      388,  389,  390,  391,  396,  397,  398,  392,  399,  400,
      401,  402,  403,  404,  405,  406,  407,  393,  394,  408,
      409,  395,  410,  411,  412,  413,  414,  415,  416,  417,
      418,  396,  397,  398,  419,  399,  400,  401,  402,  403,

      404,  405,  406,  407,  420,  421,  408,  409,  422,  410,
      411,  412,  413,  414,  415,  416,  417,  418,  423,  424,
      425,  419,  426,  427,  428,  429,  430,  431,  432,  433,
      434,  420,  421,  435,  327,  422,  306,  304,  303,  231,
      229,   49,   29,   29,   28,  423,  424,  425,   51,  426,
      427,  428,  429,  430,  431,  432,  433,  434,   50,   49,
      435,   48,   48,   48,   54,   54,   98,   98,   29,   28,
      436,    3,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436
    } ;

static yyconst flex_int16_t yy_chk[939] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    9,    9,   10,   14,
       10,   10,   10,   10,   10,  438,   10,   19,   20,   22,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   31,
       31,  334,   17,  331,  329,   10,   14,   10,   10,   10,

       10,   10,   17,   10,   19,   20,   22,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   15,   18,   15,   17,
       21,   23,   18,   24,   15,   25,   26,   27,   21,   17,
      325,   33,   18,  316,   34,   36,   37,   23,   32,   32,
       34,   23,   38,   15,   18,   15,   34,   21,   23,   18,
       24,   15,   25,   26,   27,   21,   39,   32,   33,   18,
       35,   34,   36,   37,   23,   32,   32,   34,   23,   38,
       40,   35,   41,   34,   42,   43,   44,   45,   35,   46,
       47,   53,   55,   39,   32,   56,   58,   35,   59,   60,
       61,   42,   62,   63,   64,   65,   66,   40,   35,   41,

       67,   42,   43,   44,   45,   35,   46,   47,   53,   55,
       68,   70,   56,   58,   71,   59,   60,   61,   42,   62,
       63,   64,   65,   66,   72,   73,   74,   67,   75,   76,
       77,   78,   79,   80,   81,   82,   83,   68,   70,   84,
       85,   71,   86,   87,   88,   89,   90,   91,   92,   93,
       94,   72,   73,   74,   95,   75,   76,   77,   78,   79,
       80,   81,   82,   83,   96,   97,   84,   85,   99,   86,
       87,   88,   89,   90,   91,   92,   93,   94,  102,  103,
      104,   95,  106,  107,  108,  109,  110,  112,  113,  114,
      115,   96,   97,  116,  117,   99,  118,  120,  122,  123,

      124,  125,  126,  121,  127,  102,  103,  104,  128,  106,
      107,  108,  109,  110,  112,  113,  114,  115,  121,  121,
      116,  117,  129,  118,  120,  122,  123,  124,  125,  126,
      121,  127,  130,  131,  132,  128,  133,  134,  135,  135,
      136,  137,  138,  139,  140,  121,  121,  139,  141,  129,
      142,  143,  144,  145,  146,  147,  148,  149,  150,  130,
      131,  132,  152,  133,  134,  135,  135,  136,  137,  138,
      139,  140,  153,  154,  139,  141,  156,  142,  143,  144,
      145,  146,  147,  148,  149,  150,  157,  158,  159,  152,
      160,  161,  162,  163,  164,  165,  166,  167,  170,  153,

      154,  171,  172,  156,  173,  174,  175,  176,  177,  178,
      179,  180,  181,  157,  158,  159,  182,  160,  161,  162,
      163,  164,  165,  166,  167,  170,  183,  184,  171,  172,
      185,  173,  174,  175,  176,  177,  178,  179,  180,  181,
      186,  187,  189,  182,  190,  191,  192,  195,  197,  198,
      199,  200,  201,  183,  184,  202,  203,  185,  204,  205,
      206,  207,  208,  209,  210,  211,  212,  186,  187,  189,
      213,  190,  191,  192,  195,  197,  198,  199,  200,  201,
      214,  215,  202,  203,  217,  204,  205,  206,  207,  208,
      209,  210,  211,  212,  218,  219,  225,  213,  226,  228,

      229,  231,  232,  233,  234,  235,  237,  214,  215,  239,
      240,  217,  241,  237,  243,  244,  245,  246,  247,  248,
      249,  218,  219,  225,  252,  226,  228,  229,  231,  232,
      233,  234,  235,  237,  253,  254,  239,  240,  255,  241,
      237,  243,  244,  245,  246,  247,  248,  249,  257,  258,
      259,  252,  260,  261,  262,  263,  264,  265,  266,  268,
      270,  253,  254,  271,  272,  255,  273,  274,  275,  276,
      279,  280,  281,  282,  283,  257,  258,  259,  284,  260,
      261,  262,  263,  264,  265,  266,  268,  270,  288,  290,
      271,  272,  291,  273,  274,  275,  276,  279,  280,  281,

      282,  283,  292,  293,  294,  284,  295,  297,  298,  299,
      301,  302,  303,  304,  305,  288,  290,  306,  307,  291,
      308,  309,  310,  311,  314,  315,  317,  318,  319,  292,
      293,  294,  320,  295,  297,  298,  299,  301,  302,  303,
      304,  305,  321,  323,  306,  307,  326,  308,  309,  310,
      311,  314,  315,  317,  318,  319,  327,  330,  332,  320,
      333,  335,  336,  337,  338,  339,  340,  341,  342,  321,
      323,  343,  344,  326,  345,  346,  348,  350,  351,  352,
      353,  354,  355,  327,  330,  332,  356,  333,  335,  336,
      337,  338,  339,  340,  341,  342,  357,  358,  343,  344,

      359,  345,  346,  348,  350,  351,  352,  353,  354,  355,
      360,  361,  362,  356,  363,  364,  365,  366,  367,  368,
      369,  370,  371,  357,  358,  372,  373,  359,  374,  375,
      376,  377,  378,  379,  380,  381,  383,  360,  361,  362,
      384,  363,  364,  365,  366,  367,  368,  369,  370,  371,
      385,  386,  372,  373,  387,  374,  375,  376,  377,  378,
      379,  380,  381,  383,  388,  389,  390,  384,  391,  392,
      393,  394,  395,  397,  398,  399,  400,  385,  386,  401,
      402,  387,  404,  405,  406,  407,  408,  409,  410,  411,
      412,  388,  389,  390,  413,  391,  392,  393,  394,  395,

      397,  398,  399,  400,  414,  415,  401,  402,  416,  404,
      405,  406,  407,  408,  409,  410,  411,  412,  418,  419,
      420,  413,  421,  422,  423,  425,  426,  427,  428,  429,
      431,  414,  415,  432,  312,  416,  289,  286,  285,  196,
      194,   48,   30,   29,   28,  418,  419,  420,   13,  421,
      422,  423,  425,  426,  427,  428,  429,  431,   12,   11,
      432,  437,  437,  437,  439,  439,  440,  440,    8,    5,
        3,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokens.ll"
#line 2 "tokens.ll"
struct Formula;
struct Atom;
struct Term;
struct Type;
struct UnionType;

#include <cctype>
#include <string>
#include <vector>
#include "pddl.h"


/* Current line number. */
size_t line_number;

static int make_string(const char* s, int token);
static int make_number(const char* s);
#line 822 "tokens.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 25 "tokens.ll"


#line 1005 "tokens.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 437 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 436 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 27 "tokens.ll"
return make_string(yytext, DEFINE);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "tokens.ll"
return make_string(yytext, DOMAIN_TOKEN);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "tokens.ll"
return make_string(yytext, PROBLEM);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "tokens.ll"
return REQUIREMENTS;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "tokens.ll"
return STRIPS;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 32 "tokens.ll"
return TYPING;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 33 "tokens.ll"
return NEGATIVE_PRECONDITIONS;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "tokens.ll"
return DISJUNCTIVE_PRECONDITIONS;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "tokens.ll"
return EQUALITY;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "tokens.ll"
return EXISTENTIAL_PRECONDITIONS;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "tokens.ll"
return UNIVERSAL_PRECONDITIONS;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 38 "tokens.ll"
return QUANTIFIED_PRECONDITIONS;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 39 "tokens.ll"
return CONDITIONAL_EFFECTS;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 40 "tokens.ll"
return FLUENTS;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 41 "tokens.ll"
return ADL;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 42 "tokens.ll"
return DURATIVE_ACTIONS;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 43 "tokens.ll"
return DURATION_INEQUALITIES;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 44 "tokens.ll"
return CONTINUOUS_EFFECTS;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 45 "tokens.ll"
return TYPES;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 46 "tokens.ll"
return CONSTANTS;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 47 "tokens.ll"
return PREDICATES;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 48 "tokens.ll"
return ACTION;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 49 "tokens.ll"
return DURATIVE_ACTION;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 50 "tokens.ll"
return PARAMETERS;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 51 "tokens.ll"
return DURATION;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 52 "tokens.ll"
return PRECONDITION;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 53 "tokens.ll"
return CONDITION;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 54 "tokens.ll"
return EFFECT;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 55 "tokens.ll"
return PDOMAIN;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 56 "tokens.ll"
return OBJECTS;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 57 "tokens.ll"
return INIT;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 58 "tokens.ll"
return GOAL;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 59 "tokens.ll"
return METRIC;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 60 "tokens.ll"
return AVOID_LINKS;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 61 "tokens.ll"
return make_string(yytext, OBJECT_TOKEN);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 62 "tokens.ll"
return make_string(yytext, EITHER);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 63 "tokens.ll"
return make_string(yytext, WHEN);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 64 "tokens.ll"
return make_string(yytext, NOT);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 65 "tokens.ll"
return make_string(yytext, AND);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 66 "tokens.ll"
return make_string(yytext, OR);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 67 "tokens.ll"
return make_string(yytext, IMPLY);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 68 "tokens.ll"
return make_string(yytext, EXISTS);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 69 "tokens.ll"
return make_string(yytext, FORALL);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 70 "tokens.ll"
return make_string(yytext, AT);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 71 "tokens.ll"
return make_string(yytext, OVER);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 72 "tokens.ll"
return make_string(yytext, START);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 73 "tokens.ll"
return make_string(yytext, END);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 74 "tokens.ll"
return make_string(yytext, ALL);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 75 "tokens.ll"
return make_string(yytext, MINIMIZE);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 76 "tokens.ll"
return make_string(yytext, MAXIMIZE);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 77 "tokens.ll"
return make_string(yytext, TOTAL_TIME);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 78 "tokens.ll"
return make_string(yytext, NAME);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 79 "tokens.ll"
return make_string(yytext, DURATION_VAR);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 80 "tokens.ll"
return make_string(yytext, VARIABLE);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 81 "tokens.ll"
return make_number(yytext);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 82 "tokens.ll"
return yytext[0];
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 83 "tokens.ll"
return LE;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 84 "tokens.ll"
return GE;
	YY_BREAK
case 59:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 85 "tokens.ll"
/* comment */
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 86 "tokens.ll"
/* whitespace */
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 87 "tokens.ll"
line_number++;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 88 "tokens.ll"
return ILLEGAL_TOKEN;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 "tokens.ll"
ECHO;
	YY_BREAK
#line 1403 "tokens.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 437 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 437 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 436);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 90 "tokens.ll"



/* Allocates a string containing the lowercase characters of the given
   C string, and returns the given token. */
static int make_string(const char* s, int token) {
  std::string* result = new std::string();
  for (const char* p = s; *p != '\0'; p++) {
    *result += tolower(*p);
  }
  yylval.str = result;
  return token;
}

/* Makes a number of the given string, and return the NUMBER token. */
static int make_number(const char* s) {
  yylval.num = atof(s);
  return NUMBER;
}

